name: Git Workflow Test Docker Publish Tag Publish

on:
  push:
    branches-ignore:
      - '*'
    tags:
      - '*'
  workflow_run:
    workflows: [ "Git Workflow Test PyPI Publish" ]
    types:
      - completed

jobs:
  docker-build-for-tag:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: Docker Build and Push Tag
    runs-on: ubuntu-latest
    env:
      NAMESPACE: ${{ secrets.docker_hub_organisation || 'openg2p' }}
      SERVICE_NAME: git-workflow-test
    steps:
      - uses: actions/checkout@v3
      - name: Docker build
        run: |
          TAG_NAME=$(echo ${{ github.ref }} | sed -e 's,.*/\(.*\),\1,')

          IMAGE_ID=$NAMESPACE/$SERVICE_NAME

          # Change all uppercase to lowercase
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
          VERSION=TAG_NAME
          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION
          echo IMAGE_ID=$IMAGE_ID >> $GITHUB_ENV
          echo VERSION=$VERSION >> $GITHUB_ENV

          docker build ./git-workflow-test -f ./git-workflow-test/Dockerfile-pypi \
            --tag $IMAGE_ID:$VERSION
          if [[ '${{ secrets.docker_hub_token }}' != '' && '${{ secrets.docker_hub_actor }}' != '' ]]; then
            export DOCKER_PUSH="true"
            echo DOCKER_PUSH=$DOCKER_PUSH >> $GITHUB_ENV
          fi
      - name: Docker push
        if: env.DOCKER_PUSH == 'true'
        run: |
          echo "${{ secrets.docker_hub_token }}" | docker login -u ${{ secrets.docker_hub_actor }} --password-stdin
          docker push ${{ env.IMAGE_ID }}:${{ env.VERSION }}
